### ISSUE TITLE
Crash when loading UIKit from thread that's not main

### ISSUE THREAD

**Issue by rob-keepsafe** [AppLovin/SDK-Network-Adapters#113]
Hi there, 

This is currently our number 1 crash and it's likely from loading something in `UIKit` while not on the main thread:

```
Crashed: WebThread
0  libobjc.A.dylib                0x1db109430 objc_retain + 16
1  UIKitCore                      0x20969ca24 -[UIView(Hierarchy) subviews] + 76
2  UIKitCore                      0x2096b5038 -[UIView(CALayerDelegate) _wantsReapplicationOfAutoLayoutWithLayoutDirtyOnEntry:] + 72
3  UIKitCore                      0x2096b57cc -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1460
4  QuartzCore                     0x1e051db7c -[CALayer layoutSublayers] + 184
5  QuartzCore                     0x1e0522b34 CA::Layer::layout_if_needed(CA::Transaction*) + 324
6  QuartzCore                     0x1e0481598 CA::Context::commit_transaction(CA::Transaction*) + 340
7  QuartzCore                     0x1e04afec8 CA::Transaction::commit() + 608
8  QuartzCore                     0x1e04b0d30 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
9  CoreFoundation                 0x1dbeb16bc __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
10 CoreFoundation                 0x1dbeac350 __CFRunLoopDoObservers + 412
11 CoreFoundation                 0x1dbeac100 CFRunLoopRunSpecific + 468
12 WebCore                        0x1e4d1d3e8 RunWebThread(void*) + 592
13 libsystem_pthread.dylib        0x1dbb3c25c _pthread_body + 128
14 libsystem_pthread.dylib        0x1dbb3c1bc _pthread_start + 48
15 libsystem_pthread.dylib        0x1dbb3fcf4 thread_start + 4
```

The main clues are: `Crashed: WebThread` --> `[UIView ...`. UIKit components can only be loaded from the main thread: https://developer.apple.com/documentation/code_diagnostics/main_thread_checker

We disabled AppLovin adapters (v5.0.1) for the last release and it went away and as soon as we put them back, it came right back.

Please let us know if this has been fixed in 6.4.1 or below 🙏

**Comment by thomasmso** [comment]
Thanks for reporting this @rob-keepsafe. What ad formats (inters, rewarded videos, banners) are you running? Also, are you able to reproduce this crash?

**Comment by thomasmso** [comment]
It would be tremendous if you can reproduce it. Also, please have [AppLovin SDK verbose logging](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK) turned on as well which will help us debug.

**Comment by rob-keepsafe** [comment]
@thomasmso Just want to confirm: Was this ever fixed? It's still one of our highest crash events

**Comment by thomasmso** [comment]
@rob-keepsafe - Yes, it should be fixed in our latest SDK. Let me know if that is not the case though.

**Comment by rob-keepsafe** [comment]
Thanks @thomasmso 👍 We'll try it out during one of our next release cycles
