### ISSUE TITLE
Fix MoPub deprecations

### ISSUE THREAD

**Issue by rob-keepsafe** [AppLovin/SDK-Network-Adapters#114]
Using MoPub 5.9.0, the size constants are deprecated now. According to `MPConstants.m`, the equivalents would be:

```swift
MOPUB_BANNER_SIZE = kMPPresetMaxAdSize50Height 
MOPUB_MEDIUM_RECT_SIZE = kMPPresetMaxAdSize250Height
MOPUB_LEADERBOARD_SIZE = kMPPresetMaxAdSize90Height
```

Also, this API is deprecated:

```objc
- (void)showOver:(UIWindow *)window andRender:(ALAd *)ad __deprecated_msg("Explicitly passing in an UIWindow to show an ad is deprecated as all cases show over the application's key window. Use showAd: instead.");
```

used on

```objc
[self.interstitialAd showOver: rootViewController.view.window andRender: preloadedAd];
```

**Comment by thomasmso** [comment]
Hey @rob-keepsafe - we don't actively maintain this repos, as most publishers have moved over to use the [certified adapters](https://github.com/mopub/mopub-ios-mediation/tree/master/AppLovin).

However, I removed all deprecated APIs here: https://github.com/AppLovin/SDK-Network-Adapters/pull/115

**Comment by rob-keepsafe** [comment]
@thomasmso Good to know, thanks for the link and the update!
